frontend:
  namespace: kodlnw-service-dev
  image: ghcr.io/kodlnw-software-house/front-end-service
  tag: dev
  replicas: 1
  imagePullSecrets: kodlnw-registry
  port: 80
  healthCheckPath: "/health.html"
ingress:
  host: dev.kodlnw-product.net
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  BACK_API: http://10.72.3.52:8082