frontend:
  namespace: kodlnw-service-prd
  image: ghcr.io/kodlnw-software-house/front-end-service
  tag: prd
  replicas: 1
  imagePullSecrets: kodlnw-registry
  port: 80
  healthCheckPath: "/health.html"
ingress:
  host: kodlnw-product.net
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
