frontend:
  namespace: kodlnw-service-prd
  image: ghcr.io/kodlnw-software-house/front-end-service
  tag: prd
  replicas: 1
  imagePullSecrets: kodlnw-registry
  port: 80
  healthCheckPath: "/health.html"
ingress:
  host: kodlnw-product.net
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  VUE_APP_PORT: 80
  VUE_APP_PRODUCT_API: http://kodlnw-service-back-end-prd:8082/products
  VUE_APP_BRAND_API: http://kodlnw-service-back-end-prd:8082/brands
  VUE_APP_COLOR_API: http://kodlnw-service-back-end-prd:8082/colors
  VUE_APP_IMAGE_API: http://kodlnw-service-back-end-prd:8082/picture
  VUE_APP_WARRANTY_API: http://kodlnw-service-back-end-prd:8082/warranty
