frontend:
  namespace: kodlnw-service-prd
  image: ghcr.io/Kodlnw-Software-House/front-end-service
  tag: prd
  replicas: 1
  imagePullSecrets: kodlnw-registry
  port: 8081
  healthCheckPath: "/health"
ingress:
  host: kodlnw-product.net
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2