apiVersion: v1
description: Kodlnw-product front-end Service Helm Chart
name: kodlnw-product-front-end
version: 1.0.0
appVersion: 1.0.0
home: https://kodlnw-product.net
maintainers:
  - name: Punnpapop Chalor
    email: punnapop.chalor@mail.kmutt.ac.th
sources:
  - https://github.com/Kodlnw-Software-House/front-end-vuejs.git