apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: feconfig
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
        volumeMounts:
              - name: config-volume
                mountPath: /usr/share/nginx/html/config.js
                subPath: config.js
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.frontend.port }}
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.frontend.healthCheckPath }}
            port: {{ .Values.frontend.port }}
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: {{ .Values.frontend.healthCheckPath }}
            port: {{ .Values.frontend.port }}
            scheme: HTTP
        {{- if .Values.extraEnv }}
        env:
        {{- range $key, $value := .Values.extraEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
      imagePullSecrets:
      - name: {{ .Values.frontend.imagePullSecrets }}
        
