apiVersion: v1
kind: ConfigMap
metadata:
  name: feconfig
  namespace: {{ .Values.frontend.namespace }}
data:
  config.js: |
    var config = (() => {
      return {
        "VUE_APP_API": "http://kodlnw-service-back-end-{{ .Values.frontend.tag }}"
      };
    })();
