apiVersion: v1
kind: ConfigMap
metadata:
  name: feconfig
  namespace: {{ .Values.frontend.namespace }}
data:
  config.js: |
    var config = (() => {
      return {
        "VUE_APP_API": "https://10.72.3.52:8082"
      };
    })();
